/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SImpl <em>S</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getS()
   * @generated
   */
  int S = 0;

  /**
   * The number of structural features of the '<em>S</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.TitelImpl <em>Titel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.TitelImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTitel()
   * @generated
   */
  int TITEL = 1;

  /**
   * The feature id for the '<em><b>Sentence</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITEL__SENTENCE = S_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>S</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITEL__S = S_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>V</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITEL__V = S_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Titel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITEL_FEATURE_COUNT = S_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.YImpl <em>Y</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.YImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getY()
   * @generated
   */
  int Y = 2;

  /**
   * The feature id for the '<em><b>S</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int Y__S = 0;

  /**
   * The feature id for the '<em><b>N</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int Y__N = 1;

  /**
   * The feature id for the '<em><b>R</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int Y__R = 2;

  /**
   * The feature id for the '<em><b>Ziel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int Y__ZIEL = 3;

  /**
   * The feature id for the '<em><b>Wunsch</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int Y__WUNSCH = 4;

  /**
   * The number of structural features of the '<em>Y</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int Y_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NutzenImpl <em>Nutzen</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NutzenImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNutzen()
   * @generated
   */
  int NUTZEN = 3;

  /**
   * The feature id for the '<em><b>V</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUTZEN__V = 0;

  /**
   * The number of structural features of the '<em>Nutzen</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUTZEN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.VerbNutzenImpl <em>Verb Nutzen</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.VerbNutzenImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVerbNutzen()
   * @generated
   */
  int VERB_NUTZEN = 4;

  /**
   * The feature id for the '<em><b>V</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERB_NUTZEN__V = 0;

  /**
   * The number of structural features of the '<em>Verb Nutzen</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERB_NUTZEN_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.S <em>S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>S</em>'.
   * @see org.xtext.example.mydsl.myDsl.S
   * @generated
   */
  EClass getS();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Titel <em>Titel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Titel</em>'.
   * @see org.xtext.example.mydsl.myDsl.Titel
   * @generated
   */
  EClass getTitel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Titel#getSentence <em>Sentence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sentence</em>'.
   * @see org.xtext.example.mydsl.myDsl.Titel#getSentence()
   * @see #getTitel()
   * @generated
   */
  EReference getTitel_Sentence();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Titel#getS <em>S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>S</em>'.
   * @see org.xtext.example.mydsl.myDsl.Titel#getS()
   * @see #getTitel()
   * @generated
   */
  EAttribute getTitel_S();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Titel#getV <em>V</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>V</em>'.
   * @see org.xtext.example.mydsl.myDsl.Titel#getV()
   * @see #getTitel()
   * @generated
   */
  EAttribute getTitel_V();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Y <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Y</em>'.
   * @see org.xtext.example.mydsl.myDsl.Y
   * @generated
   */
  EClass getY();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Y#getS <em>S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>S</em>'.
   * @see org.xtext.example.mydsl.myDsl.Y#getS()
   * @see #getY()
   * @generated
   */
  EAttribute getY_S();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Y#getN <em>N</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>N</em>'.
   * @see org.xtext.example.mydsl.myDsl.Y#getN()
   * @see #getY()
   * @generated
   */
  EReference getY_N();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Y#getR <em>R</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>R</em>'.
   * @see org.xtext.example.mydsl.myDsl.Y#getR()
   * @see #getY()
   * @generated
   */
  EAttribute getY_R();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Y#getZiel <em>Ziel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ziel</em>'.
   * @see org.xtext.example.mydsl.myDsl.Y#getZiel()
   * @see #getY()
   * @generated
   */
  EAttribute getY_Ziel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Y#getWunsch <em>Wunsch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Wunsch</em>'.
   * @see org.xtext.example.mydsl.myDsl.Y#getWunsch()
   * @see #getY()
   * @generated
   */
  EAttribute getY_Wunsch();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Nutzen <em>Nutzen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nutzen</em>'.
   * @see org.xtext.example.mydsl.myDsl.Nutzen
   * @generated
   */
  EClass getNutzen();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Nutzen#getV <em>V</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>V</em>'.
   * @see org.xtext.example.mydsl.myDsl.Nutzen#getV()
   * @see #getNutzen()
   * @generated
   */
  EReference getNutzen_V();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.VerbNutzen <em>Verb Nutzen</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Verb Nutzen</em>'.
   * @see org.xtext.example.mydsl.myDsl.VerbNutzen
   * @generated
   */
  EClass getVerbNutzen();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.VerbNutzen#getV <em>V</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>V</em>'.
   * @see org.xtext.example.mydsl.myDsl.VerbNutzen#getV()
   * @see #getVerbNutzen()
   * @generated
   */
  EAttribute getVerbNutzen_V();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SImpl <em>S</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getS()
     * @generated
     */
    EClass S = eINSTANCE.getS();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.TitelImpl <em>Titel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.TitelImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getTitel()
     * @generated
     */
    EClass TITEL = eINSTANCE.getTitel();

    /**
     * The meta object literal for the '<em><b>Sentence</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TITEL__SENTENCE = eINSTANCE.getTitel_Sentence();

    /**
     * The meta object literal for the '<em><b>S</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TITEL__S = eINSTANCE.getTitel_S();

    /**
     * The meta object literal for the '<em><b>V</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TITEL__V = eINSTANCE.getTitel_V();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.YImpl <em>Y</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.YImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getY()
     * @generated
     */
    EClass Y = eINSTANCE.getY();

    /**
     * The meta object literal for the '<em><b>S</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute Y__S = eINSTANCE.getY_S();

    /**
     * The meta object literal for the '<em><b>N</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference Y__N = eINSTANCE.getY_N();

    /**
     * The meta object literal for the '<em><b>R</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute Y__R = eINSTANCE.getY_R();

    /**
     * The meta object literal for the '<em><b>Ziel</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute Y__ZIEL = eINSTANCE.getY_Ziel();

    /**
     * The meta object literal for the '<em><b>Wunsch</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute Y__WUNSCH = eINSTANCE.getY_Wunsch();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NutzenImpl <em>Nutzen</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NutzenImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNutzen()
     * @generated
     */
    EClass NUTZEN = eINSTANCE.getNutzen();

    /**
     * The meta object literal for the '<em><b>V</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NUTZEN__V = eINSTANCE.getNutzen_V();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.VerbNutzenImpl <em>Verb Nutzen</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.VerbNutzenImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVerbNutzen()
     * @generated
     */
    EClass VERB_NUTZEN = eINSTANCE.getVerbNutzen();

    /**
     * The meta object literal for the '<em><b>V</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERB_NUTZEN__V = eINSTANCE.getVerbNutzen_V();

  }

} //MyDslPackage
