/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Titel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Titel#getSentence <em>Sentence</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Titel#getS <em>S</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Titel#getV <em>V</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTitel()
 * @model
 * @generated
 */
public interface Titel extends S
{
  /**
   * Returns the value of the '<em><b>Sentence</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sentence</em>' containment reference.
   * @see #setSentence(Y)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTitel_Sentence()
   * @model containment="true"
   * @generated
   */
  Y getSentence();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Titel#getSentence <em>Sentence</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sentence</em>' containment reference.
   * @see #getSentence()
   * @generated
   */
  void setSentence(Y value);

  /**
   * Returns the value of the '<em><b>S</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>S</em>' attribute.
   * @see #setS(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTitel_S()
   * @model
   * @generated
   */
  String getS();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Titel#getS <em>S</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>S</em>' attribute.
   * @see #getS()
   * @generated
   */
  void setS(String value);

  /**
   * Returns the value of the '<em><b>V</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>V</em>' attribute.
   * @see #setV(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTitel_V()
   * @model
   * @generated
   */
  String getV();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Titel#getV <em>V</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>V</em>' attribute.
   * @see #getV()
   * @generated
   */
  void setV(String value);

} // Titel
