/*
 * generated by Xtext 2.26.0
 */
package de.htwdd.sf.xtext.mydsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDslScopeProvider extends DelegatingScopeProvider {
}
