/**
 * generated by Xtext 2.26.0
 */
package de.htwdd.sf.xtext.mydsl.myDsl.impl;

import de.htwdd.sf.xtext.mydsl.myDsl.MyDslPackage;
import de.htwdd.sf.xtext.mydsl.myDsl.S;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>S</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SImpl extends MinimalEObjectImpl.Container implements S
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.S;
  }

} //SImpl
