/*
 * generated by Xtext 2.26.0
 */
package de.htwdd.sf.xtext.mydsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMyDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(de.htwdd.sf.xtext.mydsl.myDsl.MyDslPackage.eINSTANCE);
		return result;
	}
}
