/*
 * generated by Xtext 2.26.0
 */
package de.htwdd.sf.xtext.mydsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
