/*
 * generated by Xtext 2.26.0
 */
package de.htwdd.sf.xtext.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import de.htwdd.sf.xtext.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import de.htwdd.sf.xtext.mydsl.services.MyDslGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getSAccess().getGroup(), "rule__S__Group__0");
			builder.put(grammarAccess.getTitelAccess().getGroup(), "rule__Titel__Group__0");
			builder.put(grammarAccess.getYAccess().getGroup(), "rule__Y__Group__0");
			builder.put(grammarAccess.getNutzenAccess().getGroup(), "rule__Nutzen__Group__0");
			builder.put(grammarAccess.getSAccess().getSentenceAssignment_2(), "rule__S__SentenceAssignment_2");
			builder.put(grammarAccess.getTitelAccess().getSAssignment_0(), "rule__Titel__SAssignment_0");
			builder.put(grammarAccess.getTitelAccess().getVAssignment_1(), "rule__Titel__VAssignment_1");
			builder.put(grammarAccess.getYAccess().getSAssignment_1(), "rule__Y__SAssignment_1");
			builder.put(grammarAccess.getYAccess().getNAssignment_2(), "rule__Y__NAssignment_2");
			builder.put(grammarAccess.getYAccess().getRAssignment_4(), "rule__Y__RAssignment_4");
			builder.put(grammarAccess.getYAccess().getZielAssignment_5(), "rule__Y__ZielAssignment_5");
			builder.put(grammarAccess.getYAccess().getWunschAssignment_6(), "rule__Y__WunschAssignment_6");
			builder.put(grammarAccess.getNutzenAccess().getVAssignment_1(), "rule__Nutzen__VAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
