/**
 * generated by Xtext 2.26.0
 */
package de.htwdd.sf.xtext.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nutzen</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.htwdd.sf.xtext.mydsl.myDsl.Nutzen#getV <em>V</em>}</li>
 * </ul>
 *
 * @see de.htwdd.sf.xtext.mydsl.myDsl.MyDslPackage#getNutzen()
 * @model
 * @generated
 */
public interface Nutzen extends EObject
{
  /**
   * Returns the value of the '<em><b>V</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>V</em>' attribute.
   * @see #setV(String)
   * @see de.htwdd.sf.xtext.mydsl.myDsl.MyDslPackage#getNutzen_V()
   * @model
   * @generated
   */
  String getV();

  /**
   * Sets the value of the '{@link de.htwdd.sf.xtext.mydsl.myDsl.Nutzen#getV <em>V</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>V</em>' attribute.
   * @see #getV()
   * @generated
   */
  void setV(String value);

} // Nutzen
