/**
 * generated by Xtext 2.26.0
 */
package de.htwdd.sf.xtext.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>S</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.htwdd.sf.xtext.mydsl.myDsl.MyDslPackage#getS()
 * @model
 * @generated
 */
public interface S extends EObject
{
} // S
